[package]
name = "my-rust-lesson-7"
version = "0.1.0"
authors = ["gituytfjhfgdv <de_syu3939@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
